### ISSUE TITLE
teamdrive

### ISSUE THREAD

**Issue by wx69wx** [SAOJSM/TG-UPLOAD-FILE-TO-GDRIVE#1]
hi, thanks for share, it is a nice  project.
but i have problem, how to upload to my team drive? 
i change  the " self.__G_DRIVE_DIR_BASE_DOWNLOAD_URL = "https://drive.google.com/drive/folders/{}"  to "
 self.__G_DRIVE_DIR_BASE_DOWNLOAD_URL = "https://drive.google.com/drive/folders/1oxxxyyyzzz/{}"  (the 1oxxxyyyzzz is my team driver folder), but no valid....
 thanks for your advice!

**Comment by SAOJSM** [comment]
Setting it in the Telegram bot. 
Use /setfolder command to setting the folder you want to upload.

**Comment by SAOJSM** [comment]
Don't change any code in this repo, you may face repo build failed.

**Comment by wx69wx** [comment]
oh，thanks a lot for your answer~~
