### ISSUE TITLE
mega

### ISSUE THREAD

**Issue by wx69wx** [SAOJSM/TG-UPLOAD-FILE-TO-GDRIVE#2]
hi，i am shameful for asking for the mega links support. would you have plan to do this? thanks a lot!

**Comment by SAOJSM** [comment]
The answer is no. Because of the download quota limit. I will not support Mega. It will cause IP ban and many issues opened. If you want to upload mega files to google drive, you can use google colab and mega downloader. But your account may be banned because of colab abuse.
